spring.application.name=config-server
#Eureka
#eureka.instance.hostname=localhost
eureka.instance.hostname=localhost
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


#configserver
spring.cloud.config.server.git.uri=https://github.com/chandu194/application-config/